name: pysleep_torch
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pillow==6.2.1
  - pytorch==1.3.1
  - torchvision==0.4.2
  - cudatoolkit>=9.2    # mac OS users should comment out this (for CPU only) or build from the source
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pytest
  - pip
  - pip:
    - delayed-assert
    - mne
    - -e .